### ISSUE TITLE
Stops working after system restart

### ISSUE THREAD

**Issue by Tunous** [akermu/krunner-pass#4]
I'm not sure what is causing this but whenever I restart my system passwords are no longer showing in krunner even though `Pass` is listed in the list of plugins.

Re-running `install.sh` script fixes the issue but it breaks again after another reboot.

I'm running Arch Linux with KDE Plasma 5.9.5.

**Comment by akermu** [comment]
Hm, thats weird, I can't reproduce it here with the same setup.. Have you tried to just restart krunner with `kquitapp5 krunner && kstart5 --windowclass krunner krunner` after the reboot?

**Comment by Tunous** [comment]
I tried that command now and it worked but it still breaks after reboot.

**Comment by akermu** [comment]
Sorry I meant, when it breaks, does the above command fix it temporarily?

**Comment by Tunous** [comment]
Yes, it does.

**Comment by akermu** [comment]
Could you comment out [line 66 in pass.cpp](https://github.com/akermu/krunner-pass/blob/master/pass.cpp#L66) and tell me if the issue persists?

**Comment by Tunous** [comment]
That didn't fix it.

**Comment by akermu** [comment]
Is your `.password-store` at a different location than `~/`, meaning you have `PASSWORD_STORE_DIR` set?

**Comment by Tunous** [comment]
That was the issue. I had it changed to a different location. Plus I'm using `fish` shell and environment variable was set from its config, which probably was loaded after `krunner` is started.

So for me, the problem is solved. I just moved it to the original location. I don't see a reason to have it changed now anyway :)

**Comment by akermu** [comment]
Nice :)  Another way would be to set `PASSWORD_STORE_DIR` in `~/.xsession` or similar files, which would be loaded before plasmashell is executed!
