### ISSUE TITLE
Doesn't clear plasma clipboard

### ISSUE THREAD

**Issue by msmol** [akermu/krunner-pass#5]
The current buffer gets cleared after $PASSWORD_STORE_CLIP_TIME seconds, but the entry is still visible in the plasma clipboard widget.

Anyway to clear that entry as well?
Thanks!

**Comment by akermu** [comment]
Unfortunately I don't think it's possible. `pass` itself copies the password via `xclip` and after the timeout writes "sensible data" to the clipboard, which works with a single entry clipboard, not so much with a clipboard history.

Also `klipper` seems not to offer any interface to delete an entry.

I recommend to deactivate the plasma clipboard widget or at least disable the option `Save clipboard contents on exit`.

**Comment by msmol** [comment]
Okay. That's unfortunate, but thanks.

In case anyone else comes across this issue, my workaround is to set `klipper` to only hold one entry at a time. That way when `pass` writes it's "sensible data" to the clipboard, it replaces the password as the sole entry stored in `klipper`

**Comment by matthiasbeyer** [comment]
@msmol it seems that your solution with only one entry for klipper does not work anymore. At least, pass does not write "sensible data" to my clipboard.
